FROM wordpress:latest
# ENTRYPOINT []
WORKDIR /var/www/html

ENV TZ=Asia/Shanghai

RUN <<EOF
apt-get update \        
apt-get install -y git
git clone https://github.com/WordPress/sqlite-database-integration
mv sqlite-database-integration wp-content/plugins/
cp wp-content/plugins/sqlite-database-integration/db.copy wp-content/db.php
sed -i "s+{SQLITE_IMPLEMENTATION_FOLDER_PATH}+/var/www/html/wp-content/plugins/sqlite-database-integration+g" wp-content/db.php
sed -i "s+{SQLITE_PLUGIN}+sqlite-database-integration/load.php+g" wp-content/db.php
mkdir wp-content/database
touch database/.ht.sqlite
chown -R www-data:www-data wp-content/database
chmod -R 644 wp-content/database
chmod 766 wp-content/database
echo 'DENY FROM ALL' | tee wp-content/database/.htaccess > /dev/null
cp wp-config-sample.php wp-config.php
sed -i '1i \
<?php \
putenv("WORDPRESS_DB_HOST=localhost"); \
putenv("WORDPRESS_DB_USER=not-used"); \
putenv("WORDPRESS_DB_PASSWORD=not-used"); \
putenv("WORDPRESS_DB_NAME=not-used"); \
?>' index.php
EOF

# CMD ["/bin/bash"]
